name: 08b - Node.js CI/CD Demo

on: [workflow_dispatch]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Create temporary package.json if not exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "Creating demo package.json..."
            cat > package.json << 'EOL'
            {
              "name": "demo-project",
              "version": "1.0.0",
              "scripts": {
                "test": "echo 'Tests passed!'",
                "build": "mkdir -p dist && echo '<h1>Demo App</h1>' > dist/index.html",
                "lint": "echo 'No linting errors found'"
              }
            }
            EOL
            echo "Demo package.json created"
          fi
          
      - name: Install dependencies
        run: |
          # For demo purposes only - would be 'npm ci' in real scenario
          echo "Simulating npm installation..."
          mkdir -p node_modules
          echo '// Demo module' > node_modules/demo.js
      
      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create temporary package.json if not exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "Creating demo package.json..."
            cat > package.json << 'EOL'
            {
              "name": "demo-project",
              "version": "1.0.0",
              "scripts": {
                "test": "echo 'Tests passed!'",
                "build": "mkdir -p dist && echo '<h1>Demo App</h1>' > dist/index.html",
                "lint": "echo 'No linting errors found'"
              }
            }
            EOL
            echo "Demo package.json created"
          fi
      
      - name: Install dependencies
        run: |
          # For demo purposes only - would be 'npm ci' in real scenario
          echo "Simulating npm installation..."
          mkdir -p node_modules
          echo '// Demo module' > node_modules/demo.js
      
      - name: Run tests
        run: |
          npm test
          mkdir -p coverage
          echo "Demo coverage report" > coverage/index.html
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
          retention-days: 5

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Create temporary package.json if not exists
        run: |
          if [ ! -f "package.json" ]; then
            echo "Creating demo package.json..."
            cat > package.json << 'EOL'
            {
              "name": "demo-project",
              "version": "1.0.0",
              "scripts": {
                "test": "echo 'Tests passed!'",
                "build": "mkdir -p dist && echo '<h1>Demo App</h1>' > dist/index.html",
                "lint": "echo 'No linting errors found'"
              }
            }
            EOL
            echo "Demo package.json created"
          fi
      
      - name: Install dependencies
        run: |
          # For demo purposes only - would be 'npm ci' in real scenario
          echo "Simulating npm installation..."
          mkdir -p node_modules
          echo '// Demo module' > node_modules/demo.js
      
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 5

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      
      - name: Deploy to production
        run: |
          echo "Deploying application to production..."
          echo "Files to deploy:"
          ls -la dist/
          echo "Application successfully deployed!"