name: 12d - Matrix Testing Demo



on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Display environment info
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
      
      - name: Run platform-specific tests
        run: |
          echo "Running tests for ${{ matrix.os }} with Node ${{ matrix.node-version }}"
          # Replace with your actual test command
          # npm test
