name: Artifact Job

on: [push]

jobs:
    build_job_1:
        name: Build Job 1
        runs-on: ubuntu-latest
        steps:
            - name: Install CowSay 
              run: sudo apt-get install cowsay -y
            - name: Execute CowSay
              run: cowsay -f dragon "Run for cover, I'm a dragon!" >> dragon.txt
            - name: Upload Dragon text file
              uses: actions/upload-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt
            - name: Sleep for 5 seconds
              run: sleep 5
    test_job_1:
        name: Test Job 1
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file
            - name: Test file exist
              run: test -f dragon-text-file/dragon.txt && echo "File exists" || echo "File does not exist"
    deploy_job_1:
        name: Deploy Job 1
        needs: test_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file
            - name: Read File
              run: cat dragon-text-file/dragon.txt
            - name: Deploy
              run: echo "Deploying......"