name: First Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step

      - name: List and Read files

        run: |


          echo "My first github actions job"


          ls -ltra
