name: First Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step

        run: echo "Hello GitHub Actions!"

      - name: Welcome message

        run: echo "My first github actions job"

      - name: List files

        run: ls -al

      - name: Read file

        run: cat README.md
