name: First Workflow
on: [push]

jobs:
  first_job:
    runs-on: self-hosted
    steps:
      - name: Welcome message
        run: echo "My first github actions job"
      
      - name: List files
        run: ls -al
      
      - name: Read file
        run: cat README.md